SMAWeb/Controllers/ContactosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMAWeb.Models;
using SMAWeb.Filters;
using System.Xml.Xsl;
using System.IO;
using System.Xml;
using System.Xml.XPath;
using SMAWeb.Extensions;
using System.Dynamic;

namespace SMAWeb.Controllers
{
    public class ContactosController : BaseController
    {
        private Entities db = new Entities();

        //
        // GET: /Contactos/
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.CON_Contactenos.ToList());
        }

        //
        // GET: /Contactos/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id = 0)
        {
            CON_Contactenos con_contactenos = db.CON_Contactenos.Find(id);
            if (con_contactenos == null)
            {
                return HttpNotFound();
            }
            return View(con_contactenos);
        }

        //
        // GET: /Contactos/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Contactos/Create

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(CON_Contactenos con_contactenos)
        {
            if (con_contactenos.CON_Celular == null)
                con_contactenos.CON_Celular = "0";
            if (con_contactenos.CON_Telefono == null)
                con_contactenos.CON_Telefono = "0";

            if (ModelState.IsValid)
            {
                con_contactenos.CON_Fecha = DateTime.Now;
                db.CON_Contactenos.Add(con_contactenos);
                db.SaveChanges();
            }
            else
            {
                if (Request.IsAjaxRequest())
                {
                    return Json(new { wasSuccess = "False" });
                }
            }
            
            if (Request.IsAjaxRequest())
            {
                //return Json(new { wasSuccess = "True" , redirectToUrl = Url.Action("Create", "Contactos") });
                return Json(new { wasSuccess = "True" });
            }
            return RedirectToAction("Index", "Home");
            //return View(con_contactenos);
        }

        //
        // GET: /Contactos/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            CON_Contactenos con_contactenos = db.CON_Contactenos.Find(id);
            if (con_contactenos == null)
            {
                return HttpNotFound();
            }
            return View(con_contactenos);
        }

        //
        // POST: /Contactos/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CON_Contactenos con_contactenos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(con_contactenos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(con_contactenos);
        }

        //
        // GET: /Contactos/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            CON_Contactenos con_contactenos = db.CON_Contactenos.Find(id);
            if (con_contactenos == null)
            {
                return HttpNotFound();
            }
            return View(con_contactenos);
        }

        //
        // POST: /Contactos/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            CON_Contactenos con_contactenos = db.CON_Contactenos.Find(id);
            db.CON_Contactenos.Remove(con_contactenos);
            db.SaveChanges();
            var urlRedirect = Url.Action("Index");
            return Json(new { url = urlRedirect });
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult RespuestaContacto(string id, string nombre, string correo, string respuesta)
        {
            string pXml = string.Empty;
            var ppEmailTemplate = new Notification();

            ppEmailTemplate.CustomerName = nombre;
            ppEmailTemplate.Respuesta = respuesta;
            ppEmailTemplate.Destinatario = correo;

            string urlimg = Request.Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");
            var firstImage = "~/Images/logo2-blue.png";
            var formatted = firstImage.Replace("~", "");
            if (formatted.StartsWith("/"))
                formatted = formatted.Remove(0, 1);
            firstImage = urlimg + formatted;

            ppEmailTemplate.Image = firstImage;

            pXml = ppEmailTemplate.Serialize<Notification>();
            string serverPath = string.Empty;
            serverPath = base.Server.MapPath("~");
            string body = string.Empty;

            try
            {
                body = pXml.ConvertXML(Path.Combine(serverPath, @"EmailTemplates\RespuestaContacto.xslt"));
                Extensions.ExtensionHelper.SendEmail(ppEmailTemplate.Destinatario, "Respuesta a consulta en Service Market", body);

                CON_Contactenos con_contactenos = db.CON_Contactenos.Find(Convert.ToInt16(id));
                db.CON_Contactenos.Remove(con_contactenos);
                db.SaveChanges();

            }
            catch
            {

            }


            var urlRedirect = Url.Action("Index");
            return Json(new { url = urlRedirect });

        }

        public class Notification
        {
            public string CustomerName { get; set; }
            public string Respuesta { get; set; }
            public string Destinatario { get; set; }
            public string Image { get; set; }

        }

    }

}

SMAWeb/Views/Contactos/Create.cshtml
@model SMAWeb.Models.CON_Contactenos

@{
    ViewBag.Title = "Contáctenos";
}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&language=es"></script>
<style>
    .page {
        background: none repeat scroll 0 0 white;
        box-shadow: 0 1px 10px rgba(0, 0, 0, 0.25);
        /*margin: 70px 0 0;*/
        padding: 30px 12% 80px;
    }

    #map-canvas {
        height: 400px;
    }
</style>
<br />
<div class="another-page">
    <div class="container-fluid">
        <div class="row-fluid">

            <div class="span6">
                <div class="headline">
                    <h3>Formulario de contacto</h3>
                </div>
                <div class="successmessage">
                </div>

                @using (Html.BeginForm())
                {

                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()



                <h4>Por favor complete la información requerida y déjenos su mensaje. Pronto le estaremos contactando.</h4>

                <br />

                <div class="editor-label">
                    @Html.LabelFor(model => model.CON_Nombre)
                </div>

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.CON_Nombre, new { @placeholder = "Nombre", @class = "input-xlarge" }) <span class="color-red">*</span>
                </div>



                <div class="editor-label">
                    @Html.LabelFor(model => model.CON_Email)
                </div>

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.CON_Email, new { @placeholder = "Correo Electrónico", @class = "input-xlarge" }) <span class="color-red">*</span>

                </div>



                <div class="editor-label">
                    @Html.LabelFor(model => model.CON_Telefono)
                </div>

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.CON_Telefono, new { @placeholder = "Teléfono", @class = "input-xlarge" })
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.CON_Celular)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.CON_Celular, new { @placeholder = "Celular", @class = "input-xlarge" })
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.CON_Mensaje)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.CON_Mensaje, new { @placeholder = "Mensaje", @class = "input-xlarge" }) <span class="color-red">*</span>
                </div>

                <p id="req-field-desc"><span class="color-red">*</span>Indica que es un campo mandatorio en el formulario</p>

                <br />

                <div>
                    <ul style="list-style: none;">
                        <li>
                            @Html.ValidationMessageFor(model => model.CON_Nombre)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.CON_Email)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.CON_Telefono)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.CON_Celular)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.CON_Mensaje)
                        </li>
                    </ul>
                </div>

                }
                <br />

                <input type="submit" onclick="Contactenos()" value="Contactar" class="btn-u" id="submit-button" />


            </div>
            <div class="span6">

                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Contactenos -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-3305573167906515"
                     data-ad-slot="1482930789"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>

                @*MAPA DE GOOGLE MAPS - UBICACION*@
                @*<div class="headline">
                        <h3>Nuestra Ubicación</h3>
                    </div>
                    <div id="map-canvas"></div>*@

            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/SMA.js"></script>
<script type="text/javascript">

@*
    var map = null;
    var markersArray = [];
    var marker;
    //default load position

    function initialize() {


        var latlng = new google.maps.LatLng(39.4881, -75.0000);

        var mapOptions = {
            zoom: 15,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        var image = 'favicon.ico';
        var urlHelper = new UrlHelper();
        image = urlHelper.urlImage(image);

        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

        var marker = new google.maps.Marker({
            position: latlng,

            animation: google.maps.Animation.DROP,
            map: map,
            title: "Service Market Panamá",
            icon: image
        });




        //showRoutePath_1();
    }
    // End initialize function
    //remove all markers from map
    function clearOverlays() {
        if (markersArray) {
            for (var i in markersArray) {
                markersArray[i].setMap(null);
            }
        }
    }

    //remove specific marker from map
    function removeMarker(myMark) {
        if (markersArray) {
            for (var i in markersArray) {
                if (myMark == markersArray[i]['number']) {
                    console.log(markersArray[i]['number']);
                    markersArray[i].setMap(null);
                    markersArray.splice(i, 1); //removes marker from array
                    break;
                }
            }
        }
    }

    //check if marker already exist on map
    function checkMarker(number) {
        if (markersArray) {
            for (var i in markersArray) {
                if (markersArray[i]['number'] == number)
                    return true;
            }
        } else
            return false;
    }

    // Mapping variables
    var global_strokeColor = "#ED00FF";
    var global_strokeOpacity = 0.7;
    var global_strokeWeight = 6;

    //Route 1
    function showRoutePath_1() {
        //check if marker1 already on map if true do nothing
        if (checkMarker(1))
            return;
        position = new google.maps.LatLng(8.43581, -82.43475);
        var infowindow = new google.maps.InfoWindow({
            content: "Service Market Panamá"
        });
        marker = new google.maps.Marker({
            animation: google.maps.Animation.DROP,
            position: position,
            map: map
        });

        marker['number'] = 1;
        //google.maps.event.addListener(marker, 'click', toggleBounce);
        google.maps.event.addListener(marker, 'click', function () {
            infowindow.open(map, marker);
        });

        markersArray.push(marker);

        //open infowWindow with marker
        infowindow.open(map, marker);
        //setTimeout(function () { infowindow.close(); }, 5000);


    }

    function toggleBounce() {

        if (marker.getAnimation() != null) {
            marker.setAnimation(null);
        } else {
            marker.setAnimation(google.maps.Animation.BOUNCE);
        }
    }

    google.maps.event.addDomListener(window, 'load', initialize);

*@

    function Contactenos() {
        if ($('#CON_Nombre').val() == "" || $('#CON_Email').val() == "" || $('#CON_Mensaje').val() == "") {
            $.gritter.add({
                title: 'Datos Insuficientes',
                text: 'Para poder enviar su mensaje es necesario que complete debidamente todos los campos requeridos (*). Gracias por preferirnos.'
            });
        }
        else {
            CONTACTOS.Create('@Url.Action("Create", "Contactos")', $('#CON_Nombre').val(), $('#CON_Telefono').val(), $('#CON_Celular').val(), $('#CON_Email').val(), $('#CON_Mensaje').val())
        }
    }

</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SMAWeb/Views/Contactos/Edit.cshtml
@model SMAWeb.Models.CON_Contactenos
@{
    ViewBag.Title = "Responder a un contacto";
}
<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Editar Contactos</h3>
            </div>

            @using (Html.BeginForm())
            {
 @Html.AntiForgeryToken()
 @Html.ValidationSummary(true)  
                <div id="CON_Id">
 @Html.HiddenFor(model => model.CON_Id)
                   </div>                 
                



                <div class="span5">
                    <div class="form-horizontal">
                        <div class="control-group" style="margin-bottom: 0px;">
                            <label class="control-label"><strong>@Html.DisplayNameFor(model => model.CON_Nombre)</strong></label>
                            <div class="controls" id="txtNombre">
                                @Html.DisplayFor(model => model.CON_Nombre)
                            </div>
                        </div>
                        <div class="control-group" style="margin-bottom: 0px;">
                            <label class="control-label"><strong>@Html.DisplayNameFor(model => model.CON_Telefono)</strong></label>
                            <div class="controls">
                                @Html.DisplayFor(model => model.CON_Telefono)
                            </div>
                        </div>
                        <div class="control-group" style="margin-bottom: 0px;">
                            <label class="control-label"><strong>@Html.DisplayNameFor(model => model.CON_Celular)</strong></label>
                            <div class="controls">
                                @Html.DisplayFor(model => model.CON_Celular)
                            </div>
                        </div>
                        <div class="control-group" style="margin-bottom: 0px;">
                            <label class="control-label"><strong>@Html.DisplayNameFor(model => model.CON_Email)</strong></label>
                            <div class="controls" id="txtEmail">
                                @Html.DisplayFor(model => model.CON_Email)
                            </div>
                        </div>
                        <div class="control-group" style="margin-bottom: 0px;">
                            <label class="control-label"><strong>@Html.DisplayNameFor(model => model.CON_Fecha)</strong></label>
                            <div class="controls">
                                @Html.DisplayFor(model => model.CON_Fecha)
                            </div>
                        </div>
                        <div class="control-group" style="margin-bottom: 0px;">
                            <label class="control-label"><strong>@Html.DisplayNameFor(model => model.CON_Mensaje)</strong></label>
                            <div class="controls">
                                @Html.DisplayFor(model => model.CON_Mensaje)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="editor-label">
                        <label>
                       <strong>Respuesta</strong></label>
                    </div>
                    <div class="editor-field">
                        @Html.TextArea("txtRespuesta", new { @placeholder = "Respuesta", @class = "span12", @rows = "8" })
                    </div>
                    <p>
                    
                </p>
                </div>
                   
                


                <div class="span12">
                
                </div>
            }
            <input type="submit" value="Responder" id="btnResponder" class="btn-u pull-right" />
            <div class="span12">
                <br />
                @Html.ActionLink("Regresar", "Index")
            </div>
            

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }
            
        </div>
    </div>
</div>
<script>
    jQuery(function () {
        jQuery("#btnResponder").click(function () {
            
            var nombre = jQuery("#txtNombre").text().trim();
            var email = jQuery("#txtEmail").text().trim();
            var respuesta = jQuery("#txtRespuesta").val();
            var id = jQuery('#CON_Id input').val();


            jQuery.ajax({
                url: '@Url.Action("RespuestaContacto", "Contactos")',
                type: 'post',
                data: { id: id, nombre : nombre, correo : email, respuesta : respuesta },
                beforeSend: function () {
                    showProgress('@Url.Content("~/images/loading.gif")');
                },
                complete: function (data) {
                    hideProgress();
                },
                success: function (data) {
                    window.location = data.url;
                 },
                 error: function (xhr) {
                     if (xhr.status == 403) {
                         var response = $.parseJSON(xhr.responseText);
                         window.location = response.LogOnUrl;
                     }
                     else {
                         alert(xhr.responseText, 'Ha ocurrido un error.');
                     }
                 }
            });

        });
    });

    
    var $ki = jQuery.noConflict();
    function showProgress(loadingImgSrc) {
        $ki.blockUI({
            message: '<p>Por favor espere mientra se procesa la solicitud...</p><img src="' + loadingImgSrc + '" /> <br>',
            css: {
                width: '450px',
                border: 'none',
                padding: '15px',
                backgroundColor: '#fafafa',
                'border-radius': '10px',
                opacity: .95,
                color: '#000',
                'font-size': '18px',
                'box-shadow': '0px 0px 12px rgba(0,0,0,.6)',
                'z-index': '9999'
            }
        });
    }

    function hideProgress() {
        $ki.unblockUI();
    }

</script>

SMAWeb/Views/Contactos/Index.cshtml
@model IEnumerable<SMAWeb.Models.CON_Contactenos>

@{
    ViewBag.Title = "Index";
}

<link href="@Url.Content("~/Content/jpages/jPages.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/jpages/animate.css")" rel="stylesheet" type="text/css" />
@*<link href="@Url.Content("~/Content/jpages/style.css")" rel="stylesheet" type="text/css" />*@
<script src="@Url.Content("~/Scripts/jpage/jPages.min.js")" type="text/javascript"></script>

<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Formulario de Contactos</h3>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.CON_Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CON_Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CON_Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CON_Mensaje)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CON_Fecha)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="divBody">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CON_Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CON_Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CON_Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CON_Mensaje)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CON_Fecha)
                            </td>
                            <td>
            
                                @Html.ActionLink("Responder", "Edit", new { id = item.CON_Id }, new { @class = "btn-u"}) 
                                <button type="submit" onclick="DeleteContacto('@item.CON_Id')" class="btn-u">Eliminar</button>
                                
            
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="8">
                            <div class="holder" style="float: left">
                            </div>
                        </td>
                    </tr>
                </tfoot>

            </table>
        </div>
    </div>
</div>

<script>

    var $jpage = jQuery.noConflict();
    $jpage(function () {
        $jpage("div.holder").jPages({
            containerID: "divBody",
            //              previous: "←",
            //              next: "→",
            first: "Primera",
            previous: "Anterior",
            next: "Siguiente",
            last: "Última",
            perPage: 5,
            delay: 20
        });
    });

    function DeleteContacto(id) {
        
        $.ajax({
            url: '@Url.Action("Delete", "Contactos")',
            type: 'post',
            data: { id : id},
            @*beforeSend: function () {
                showProgress('@Url.Content("~/images/loading.gif")');
            },
            complete: function (data) {
                hideProgress();
            },*@
            success: function (data) {
                window.location = data.url;
            },
            error: function (xhr) {
                if (xhr.status == 403) {
                    var response = $.parseJSON(xhr.responseText);
                    window.location = response.LogOnUrl;
                }
                else {
                    alert(xhr.responseText, 'An error has ocurred');
                }
            }
        });
    }
</script>