SMAWeb/Controllers/BlackListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMAWeb.Models;

namespace SMAWeb.Controllers
{
    public class BlackListController : Controller
    {
        private Entities db = new Entities();

        //
        // GET: /BlackList/

        public ActionResult Index()
        {
            return View(db.BL_BlackList.ToList());
        }

        //
        // GET: /BlackList/Details/5

        public ActionResult Details(int id = 0)
        {
            BL_BlackList bl_blacklist = db.BL_BlackList.Find(id);
            if (bl_blacklist == null)
            {
                return HttpNotFound();
            }
            return View(bl_blacklist);
        }

        //
        // GET: /BlackList/Create

        public ActionResult Create()
        {
            BL_BlackList BL = new BL_BlackList();
            BL.BL_Id = 1;
            return View(BL);
        }

        //
        // POST: /BlackList/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(BL_BlackList bl_blacklist)
        {
            if (ModelState.IsValid)
            {
                db.BL_BlackList.Add(bl_blacklist);
                db.SaveChanges();
                if (Request.IsAjaxRequest())
                {
                    return Json(new { wasSuccess = true });
                }
                return RedirectToAction("Index");
            }
            if (Request.IsAjaxRequest())
            {
                return Json(new { wasSuccess = false });
            }
            return View(bl_blacklist);

        }

        //
        // GET: /BlackList/Edit/5

        public ActionResult Edit(int id = 0)
        {
            BL_BlackList bl_blacklist = db.BL_BlackList.Find(id);
            if (bl_blacklist == null)
            {
                return HttpNotFound();
            }
            return View(bl_blacklist);
        }

        //
        // POST: /BlackList/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BL_BlackList bl_blacklist)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bl_blacklist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bl_blacklist);
        }

        //
        // GET: /BlackList/Delete/5

        public ActionResult Delete(int id = 0)
        {
            BL_BlackList bl_blacklist = db.BL_BlackList.Find(id);
            if (bl_blacklist == null)
            {
                return HttpNotFound();
            }
            return View(bl_blacklist);
        }

        //
        // POST: /BlackList/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BL_BlackList bl_blacklist = db.BL_BlackList.Find(id);
            db.BL_BlackList.Remove(bl_blacklist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SMAWeb/Views/BlackList/Create.cshtml
@model SMAWeb.Models.BL_BlackList

@{
    ViewBag.Title = "Create";
}

<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Crear Black List</h3>
            </div>

            <div class="message">
            </div>

            @using (Ajax.BeginForm("Create", "BlackList", new AjaxOptions { HttpMethod = "Post", OnSuccess = "CreateBlackList" }))
            {

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.BL_Id)
                    


       
                <div class="editor-label">
                    @Html.LabelFor(model => model.BL_Descripcion)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.BL_Descripcion)

                </div>

                <p>
                    <input type="submit" value="Crear" class="btn-u btn-u-orange" />
                </p>
                <ul style="list-style: none;">
                    <li>@Html.ValidationMessageFor(model => model.BL_Descripcion)
                    </li>
                </ul>
            }

        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SMAWeb/Views/BlackList/Edit.cshtml
@model SMAWeb.Models.BL_BlackList

@{
    ViewBag.Title = "Edit";
}

<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Editar Categoría</h3>
            </div>


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

    
                @Html.HiddenFor(model => model.BL_Id)

                <div class="editor-label">
                    @Html.LabelFor(model => model.BL_Descripcion)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.BL_Descripcion)
                </div>

                <p>
                    <input type="submit" value="Guardar" class="btn-u btn-u-orange" />
                </p>
                <ul style="list-style: none;">
                    <li>@Html.ValidationMessageFor(model => model.BL_Descripcion)
                    </li>
                </ul>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }
        </div>
    </div>
</div>

SMAWeb/Views/BlackList/Index.cshtml
@model IEnumerable<SMAWeb.Models.BL_BlackList>

@{
    ViewBag.Title = "Index";
}

<link href="@Url.Content("~/Content/jpages/jPages.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/jpages/animate.css")" rel="stylesheet" type="text/css" />
@*<link href="@Url.Content("~/Content/jpages/style.css")" rel="stylesheet" type="text/css" />*@
<script src="@Url.Content("~/Scripts/jpage/jPages.min.js")" type="text/javascript"></script>
<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Formulario de Categoría</h3>
            </div>

            <p>
                @Html.ActionLink("Nuevo", "Create")
            </p>

            <table class="table table-striped">
                <thead>

                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.BL_Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.BL_Descripcion)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="divBody">

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BL_Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BL_Descripcion)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.BL_Id }) @*|
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3">
                            <div class="holder" style="float: left">
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<script>

    var $jpage = jQuery.noConflict();
    $jpage(function () {
        $jpage("div.holder").jPages({
            containerID: "divBody",
            //              previous: "?",
            //              next: "?",
            first: "Primera",
            previous: "Anterior",
            next: "Siguiente",
            last: "Última",
            perPage: 15,
            delay: 20
        });
    });
</script>