SMAWeb/Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMAWeb.Models;
using SMAWeb.Filters;
using WebMatrix.WebData;
using SMAWeb.Extensions;
using Newtonsoft.Json.Linq;
using System.Transactions;

namespace SMAWeb.Controllers
{
    public class AnunciosController : BaseController
    {
        private Entities db = new Entities();

        //
        // GET: /Anuncios/
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var allAnunciosList = new List<AN_Anuncios>();
            List<AnunciosViewModel> viewModelAnuncios = new List<AnunciosViewModel>();
            using (Entities model = new Entities())
            {
                allAnunciosList = model.AN_Anuncios.OrderByDescending(c => c.AN_Fecha).ToList();
                foreach (var item in allAnunciosList)
                {
                    string username = item.UserProfile.Name;
                    string statusDesc = item.ST_Estatus.ST_Descripcion;
                    var categoria = item.SBS_SubCategoriaServicio.CD_CategoriaServicio.CD_Descripcion;
                    var firstImage = string.Empty;
                    if (item.AE_AnunciosExtras.FirstOrDefault() != null)
                    {
                        firstImage = item.AE_AnunciosExtras.FirstOrDefault().AN_ImagenUrl;
                    }

                    string urlimg = Request.Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");
                    var formatted = firstImage.Replace("~", "");
                    if (formatted.StartsWith("/"))
                        formatted = formatted.Remove(0, 1);
                    firstImage = urlimg + formatted;


                    viewModelAnuncios.Add(new AnunciosViewModel
                    {
                        Usuario = username,
                        EstatusDescription = statusDesc,
                        AnunciosInfo = item,
                        CategoriaDescripcion = categoria,
                        FirstImage = firstImage
                    });

                }
            }
            if (viewModelAnuncios == null || viewModelAnuncios.Count == 0)
            {
                return HttpNotFound();
            }
            return View(viewModelAnuncios);
        }


        [Authorize(Roles = "Users, Admin")]
        public ActionResult GetAnunciosByUser()
        {
            int UserId = UserId = WebSecurity.CurrentUserId;
            var allAnunciosList = new List<AN_Anuncios>();
            List<AnunciosViewModel> viewModelAnuncios = new List<AnunciosViewModel>();
            using (Entities model = new Entities())
            {
                //allAnunciosList = model.AN_Anuncios.OrderBy(c => c.AN_Fecha).Where(acc => acc.ST_Id == 1 && acc.UserId == UserId).ToList();
                allAnunciosList = model.AN_Anuncios.OrderBy(c => c.AN_Fecha).Where(acc => acc.UserId == UserId && (acc.ST_Id == 1 | acc.ST_Id == 2 | acc.ST_Id == 9)).ToList();


                var categoriasList = new List<Categoria>();
                db.CD_CategoriaServicio.ToList().ForEach(c =>
                {
                    var subCatList = new List<SubCategorias>();

                    c.SBS_SubCategoriaServicio.ToList().ForEach(sb =>
                    {
                        subCatList.Add(new SubCategorias { SubCatId = sb.SBS_Id, SubCatDesc = sb.SBS_Descripcion });
                    });
                    categoriasList.Add(new Categoria
                    {
                        CatId = c.CD_Id,
                        CatDesc = c.CD_Descripcion,
                        SubCatCollection = subCatList
                    });
                });



                ViewBag.Categories = categoriasList;

                foreach (var item in allAnunciosList)
                {
                    string username = item.UserProfile.Name;
                    string statusDesc = item.ST_Estatus.ST_Descripcion;
                    var categoria = item.SBS_SubCategoriaServicio.CD_CategoriaServicio.CD_Descripcion;
                    var firstImage = string.Empty;
                    if (item.AE_AnunciosExtras.FirstOrDefault() != null)
                    {
                        firstImage = item.AE_AnunciosExtras.FirstOrDefault().AN_ImagenUrl;
                    }
                    else
                    {
                        firstImage = item.UserProfile.Image == null ? "~/Images/No_Profile.jpg" : item.UserProfile.Image;
                    }

                    var getRating = model.SEL_ValoracionAnuncios(item.AN_Id).FirstOrDefault();


                    string urlimg = Request.Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");
                    var formatted = firstImage.Replace("~", "");
                    if (formatted.StartsWith("/"))
                        formatted = formatted.Remove(0, 1);
                    firstImage = urlimg + formatted;


                    viewModelAnuncios.Add(new AnunciosViewModel
                    {
                        Usuario = username,
                        EstatusDescription = statusDesc,
                        AnunciosInfo = item,
                        CategoriaDescripcion = categoria,
                        FirstImage = firstImage,
                        Rating = getRating
                    });

                }
            }
            if (viewModelAnuncios == null || viewModelAnuncios.Count == 0)
            {
                //return HttpNotFound();
            }
            return View(viewModelAnuncios);

        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult GetLastAnuncios()
        {
            var allAnunciosList = new List<AN_Anuncios>();
            List<AnunciosViewModel> viewModelAnuncios = new List<AnunciosViewModel>();
            using (Entities model = new Entities())
            {
                allAnunciosList = model.AN_Anuncios.OrderByDescending(day => day.AN_Fecha).Where(acc => acc.ST_Id == 1).Take(3).ToList();

                foreach (var item in allAnunciosList)
                {
                    string username = item.UserProfile.Name;
                    string statusDesc = item.ST_Estatus.ST_Descripcion;
                    var categoria = item.SBS_SubCategoriaServicio.CD_CategoriaServicio.CD_Descripcion;
                    var firstImage = string.Empty;
                    if (item.AE_AnunciosExtras.FirstOrDefault() != null)
                    {
                        firstImage = item.AE_AnunciosExtras.FirstOrDefault().AN_ImagenUrl;
                    }
                    else
                    {
                        firstImage = item.UserProfile.Image == null ? "~/Images/No_Profile.jpg" : item.UserProfile.Image;
                    }

                    string urlimg = Request.Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");
                    var formatted = firstImage.Replace("~", "");
                    if (formatted.StartsWith("/"))
                        formatted = formatted.Remove(0, 1);
                    firstImage = urlimg + formatted;

                    string descripcion = string.Empty;
                    descripcion = item.AN_Descripcion.Substring(0, item.AN_Descripcion.Length < 112 ? item.AN_Descripcion.Length : 112);
                    if (descripcion.LastIndexOf(' ') > 0)
                        descripcion = descripcion.Substring(0, descripcion.LastIndexOf(' '));

                    descripcion += "...";

                    item.AN_Descripcion = descripcion;

                    viewModelAnuncios.Add(new AnunciosViewModel
                    {
                        Usuario = username,
                        EstatusDescription = statusDesc,
                        AnunciosInfo = item,
                        CategoriaDescripcion = categoria,
                        FirstImage = firstImage
                    });

                }
            }
            if (viewModelAnuncios == null || viewModelAnuncios.Count == 0)
            {
                return HttpNotFound();
            }
            return Json((viewModelAnuncios).SerializeToJson());

        }


        public ActionResult GetInformationAnuncios(FormCollection form)
        {
            var allAnunciosList = new List<AN_Anuncios>();

            var category = string.IsNullOrEmpty(form["Categoria"]) ? default(int) : int.Parse(form["Categoria"].ToString());
            var subcategoria = string.IsNullOrEmpty(form["SubCategoria"]) ? default(int) : int.Parse(form["SubCategoria"].ToString());
            var lugar = string.IsNullOrEmpty(form["Lugar"]) ? default(string) : form["Lugar"].ToString();
            var descripcion = string.IsNullOrEmpty(form["Descripcion"]) ? default(string) : form["Descripcion"].ToString();


            List<AnunciosViewModel> viewModelAnuncios = new List<AnunciosViewModel>();
            using (Entities model = new Entities())
            {

                allAnunciosList = db.Get_AdvanceSearch(category, subcategoria, descripcion, lugar).ToList();

                foreach (var item in allAnunciosList)
                {
                    string username = item.UserProfile.Name;
                    string statusDesc = item.ST_Estatus.ST_Descripcion;
                    var categoria = item.SBS_SubCategoriaServicio.CD_CategoriaServicio.CD_Descripcion;
                    var firstImage = string.Empty;
                    if (item.AE_AnunciosExtras.FirstOrDefault() != null)
                    {
                        firstImage = item.AE_AnunciosExtras.FirstOrDefault().AN_ImagenUrl;
                    }
                    else
                    {
                        firstImage = item.UserProfile.Image == null ? "~/Images/No_Profile.jpg" : item.UserProfile.Image;

SMAWeb/Views/Anuncios/Create.cshtml
@model SMAWeb.Models.AN_Anuncios

@{
    ViewBag.Title = "Create";
}

<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Crear Anuncio</h3>
            </div>

            @using (Ajax.BeginForm("Create", "Anuncios", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "content", OnSuccess = "Success" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.AN_Id)
                @Html.HiddenFor(model => model.UserId, "UserProfile")
                @Html.HiddenFor(model => model.AN_Fecha) 
                @Html.HiddenFor(model => model.AN_FechaExpiracion)
                @Html.HiddenFor(model => model.ST_Id)
               
                <div class="row-fluid">
                    <div class="span12">
                        <div class="controls form-inline">
                            @Html.LabelFor(model => model.AN_Titulo)<span class="color-red"> *</span>
                        </div>
                        <div class="editor-field">
                            @Html.TextBoxFor(model => model.AN_Titulo, new { @placeholder = "Título del Anuncio", @class = "input-block-level" })

                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">

                        <div class="span4">
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.PA_Id)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @*@Html.DropDownList("PA_Id", (IEnumerable<SelectListItem>)ViewBag.PA_Id, "Selecione el país", new { @class = "input-block-level" })  *@
                                @Html.DropDownListFor(model => model.PA_Id, (IEnumerable<SelectListItem>)ViewBag.PA_Id, "Selecione el país", new { @class = "input-block-level" })
                            </div>
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.CD_Id)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                               @*@Html.DropDownList("CD_Id", (IEnumerable<SelectListItem>)ViewBag.CD_Id, "Selecione la categoría", new { @class = "input-block-level" })*@
                                 @Html.DropDownListFor(model => model.CD_Id, (IEnumerable<SelectListItem>)ViewBag.CD_Id, "Selecione la categoría", new { @class = "input-block-level" })
                            </div>
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.SBS_Id) 
                            </div>
                            <div class="editor-field">
                             @*   @Html.DropDownList("SBS_Id", (IEnumerable<SelectListItem>)ViewBag.SBS_Id, "Selecione la subcategoría", new { @class = "input-block-level" })*@
                                @Html.DropDownListFor(model => model.SBS_Id, (IEnumerable<SelectListItem>)ViewBag.SBS_Id, "Selecione la subcategoría", new { @class = "input-block-level" })
                            </div>
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.AN_Telefono)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.AN_Telefono, new { @placeholder = "Teléfono", @class = "input-block-level" })
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(model => model.AN_Celular)
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.AN_Celular, new { @placeholder = "Teléfono 2", @class = "input-block-level" })
                            </div>
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.AN_Area)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @Html.TextAreaFor(model => model.AN_Area, new { @placeholder = "Lugar del Anuncio", @class = "input-block-level", @rows = "3" })

                            </div>
                        </div>
                        <div class="span4">
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.AN_Descripcion)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @Html.TextAreaFor(model => model.AN_Descripcion, new { @placeholder = "Descripción del Anuncio", @class = "input-block-level", @rows = "14" })

                            </div>


                        </div>
                        <div class="span4">

                            <div class="headline">
                                <h3>Como publicar</h3>
                            </div>
                            <div class="info-blocks alert alert-info alert-block">

                                <div class="info-blocks-in">

                                    <h4 style="color: #c09853"><i class="icon-bell icon-info-blocks" style="vertical-align: middle;"></i>Paso # 1</h4>
                                    <h5 class="text-info">Completa los datos de tu anuncio</h5>
                                </div>
                                <br />
                                <div class="info-blocks-in">

                                    <h4 style="color: #c09853"><i class="icon-bell icon-info-blocks" style="vertical-align: middle;"></i>Paso # 2</h4>
                                    <h5 class="text-info">Carga los recursos que se utilizarán dentro de tu anuncio publicado.</h5>
                                </div>


                            </div>
                        </div>

                    </div>

                </div> 
            
                <p>
                    @Html.ActionLink("Finalizar", "Index", "Home", null, new { @class = "btn-u pull-right submitback" })
                </p>

                <div id="content">
                </div>


                <div class="pull-right">
                    @Html.ActionLink("Regresar", "GetAnunciosByUser", "Anuncios", null, new { @class = "btn-u btn-u-orange" })

                    <input type="submit" value="Crear Anuncio" class="btn-u submitbtn" />

                </div>
                <div>
                    <ul style="list-style: none;">
                        <li>
                            @Html.ValidationMessageFor(model => model.AN_Titulo)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.PA_Id)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.CD_Id)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.SBS_Id)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.AN_Telefono)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.AN_Celular)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.AN_Area)
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.AN_Descripcion)
                        </li>
                    </ul>
                </div>
                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
                  
            }



        </div>
    </div>
</div>

<script src="~/Scripts/SMA.js"></script>
<script>
    jQuery(document).ready(function () {
        jQuery('.submitback').hide();
        HOME.ChangeCategory("CD_Id", '@Url.Action("GetSubCategories", "SubCategoriaServicio")');
        ANUNCIOS.ValidateCreatePage('@Url.Action("ValidateAnuncioCreate", "Anuncios")', '@Url.Action("Index", "Home")');
    });


    function Success() {
        //$("#content").prepend(' <br /> <br /><div class="alert alert-success fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><strong>Recursos! </strong> El anuncio esta habilitado para subir sus recursos.</div>');
        //$('.alert').alert();
        //$('.alert').fadeOut(10000)


        $.gritter.add({
            title: 'Anuncio Creado',
            text: 'Su anuncio ha sido creado satisfactoriamente. Ahora puede agregar imágenes relacionadas a su anuncio. Gracias por preferirnos.'
        });

        $('.submitbtn').hide();
        $('.submitback').show();
    }

    @*  jQuery("#CD_Id").change(function () {
        $.ajax({
            dataType: "json",
            type: 'post',
            url: '@Url.Action("GetSubCategories", "SubCategoriaServicio")',
            data: { Cat: parseInt(jQuery("#CD_Id").val()) },
            success: function (data) {
                var result = JSON.parse(data);
                var select = $('#SBS_Id');
                if (select.prop) {
                    var options = select.prop('options');
                }
                else {
                    var options = select.attr('options');
                }
                $('option', select).remove();
                $.each(result.$values, function (key, val) {
                    options[options.length] = new Option(val.SBS_Descripcion, val.SBS_Id);
                });
            },
            error: function (a, b, c) {

            },
        });
    });*@

</script>

SMAWeb/Views/Anuncios/Edit.cshtml
@model SMAWeb.Models.AN_Anuncios

@{
    ViewBag.Title = "Edit";
}

<script src="~/Scripts/CustomScript/behavior.js"></script>
<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Editar Anuncio</h3>
            </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.AN_Id)
                @Html.HiddenFor(model => model.UserId, "UserProfile")
                @Html.HiddenFor(model => model.AN_Fecha) 
                @Html.HiddenFor(model => model.AN_FechaExpiracion)
                @Html.HiddenFor(model => model.ST_Id)
               
                <div class="row-fluid">
                    <div class="span12">
                        <div class="controls form-inline">
                            @Html.LabelFor(model => model.AN_Titulo)<span class="color-red"> *</span>
                        </div>
                        <div class="editor-field">
                            @Html.TextBoxFor(model => model.AN_Titulo, new { @placeholder = "Título del Anuncio", @class = "input-block-level" })

                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">

                        <div class="span4">
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.PA_Id)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @*  @Html.DropDownList("PA_Id", (IEnumerable<SelectListItem>)ViewBag.PA_Id, new { @class = "input-block-level" })*@
                                @Html.DropDownListFor(model => model.PA_Id, ViewData["Paises"] as SelectList, new { @class = "input-block-level", @paid = Model.PA_Id })

                            </div>
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.CD_Id)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">

                                @Html.DropDownList("CD_Id", (IEnumerable<SelectListItem>)ViewBag.CD_Id, new { @class = "input-block-level" , @cdid = Model.CD_Id })

                            </div>
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.SBS_Id)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownList("SBS_Id", (IEnumerable<SelectListItem>)ViewBag.SBS_Id, new { @class = "input-block-level", @scid = Model.SBS_Id })
                            </div>
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.AN_Telefono)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.AN_Telefono, new { @placeholder = "Teléfono", @class = "input-block-level" })

                            </div>

                            <div class="editor-label">
                                @Html.LabelFor(model => model.AN_Celular)
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.AN_Celular, new { @placeholder = "Celular", @class = "input-block-level" })

                            </div>

                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.AN_Area)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @Html.TextAreaFor(model => model.AN_Area, new { @placeholder = "Lugar del Anuncio", @class = "input-block-level", @rows = "3" })

                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(model => model.ST_Id)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownList("ST_Id", (IEnumerable<SelectListItem>)ViewBag.ST_Id, new { @class = "input-block-level" })

                            </div>

                        </div>
                        <div class="span8">
                            <div class="controls form-inline">
                                @Html.LabelFor(model => model.AN_Descripcion)<span class="color-red"> *</span>
                            </div>
                            <div class="editor-field">
                                @Html.TextAreaFor(model => model.AN_Descripcion, new { @placeholder = "Descripción del Anuncio", @class = "input-block-level", @rows = "15" })

                            </div>


                        </div>
                        <p>
                            <input type="submit" value="Guardar" class="btn-u pull-right" />
                        </p>

                    </div>
                    <br />
                    <div>
                        <ul style="list-style: none;">
                            <li>@Html.ValidationMessageFor(model => model.AN_Titulo)</li>
                            <li>@Html.ValidationMessageFor(model => model.PA_Id)</li>
                            <li>@Html.ValidationMessageFor(model => model.CD_Id)</li>
                            <li>@Html.ValidationMessageFor(model => model.SBS_Id)</li>
                            <li>@Html.ValidationMessageFor(model => model.AN_Telefono)</li>
                            <li>@Html.ValidationMessageFor(model => model.AN_Celular)</li>
                            <li>@Html.ValidationMessageFor(model => model.AN_Descripcion)</li>
                            <li>@Html.ValidationMessageFor(model => model.ST_Id)</li>
                            <li>@Html.ValidationMessageFor(model => model.AN_Descripcion)</li>
                        </ul>

                        <div class="span12">
                            <div class="headline">
                                <h3>Multimedia disponible en el Anuncio</h3>
                            </div>
                            <ul class="thumbnails">

                                @foreach (var item in Model.AE_AnunciosExtras.ToList().Take(4))
                                {
                                    <li class="span3" itemid="@item.AE_Id">
                                        <div class="thumbnail-style thumbnail-kenburn">
                                            <div class="thumbnail-img">
                                                <div class="overflow-hidden">
                                                    <img src="@Url.Content(item.AN_ImagenUrl)" alt="" />
                                                </div>
                                                <a class="btn-more btn-u hover-effect" onclick="DeleteRecurso('@item.AE_Id')" href="#">Eliminar</a>
                                            </div>
                                        </div>
                                    </li>
                                }

                            </ul>
                        </div>
                    </div>




                </div>
                
            }

            <div class="row-fluid">
                <div class="span12 divLoader">
                    @if (ViewBag.ResourcesCount < 4)
                    {
                        @Html.Partial("LoadUplaoder")
                    }
                </div>
                <div>
                    @Html.ActionLink("Regresar", "GetAnunciosByUser", "Anuncios", null, new { @class = "btn-u" })
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/SMA.js"></script>
<script>
    function DeleteRecurso(id) {
        ANUNCIOS.DeleteResource(id, '@Url.Content("~/HttpHandler/UploadHandler.ashx?id=")', '@Url.Action("LoadUplaoder", "Anuncios")');
    }

    jQuery(document).ready(function () {
        HOME.ChangeCategory("CD_Id", '@Url.Action("GetSubCategories", "SubCategoriaServicio")');
        ANUNCIOS.SetDropDowns();
    });

    jQuery(document).ready(function () {
     
    });
</script>