SMAWeb/Controllers/SolicitudServicioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMAWeb.Models;
using WebMatrix.WebData;
using SMAWeb.Filters;
using System.Xml.Xsl;
using System.IO;
using System.Xml;
using System.Xml.XPath;
using SMAWeb.Extensions;
using System.Dynamic;

using System.Web.Security;


namespace SMAWeb.Controllers
{
    public class SolicitudServicioController : BaseController
    {
        private Entities db = new Entities();

        //
        // GET: /SolicitudServicio/
        [Authorize(Roles = "Users, Admin")]
        public ActionResult Index()
        {
            var mysol = new List<SolicitudViewModel>();
            using (var db = new Entities())
            {
                var solicitudes = db.SS_SolicitudServicio;
                Func<int, string> x = value =>
                {
                    switch (value)
                    {
                        case 1: return "Activo";
                        case 2: return "Cancelado";
                        case 3: return "Realizado";
                        case 4: return "En espera de Review";
                        case 5: return "Completado";
                        case 6: return "Iniciar Tarea";
                        case 7: return "A revisión";
                        case 8: return "Eliminado";
                        case 9: return "Expirado";
                        default: return "";
                    }
                };
                solicitudes.ToList().ForEach((sol) =>
                {
                    mysol.Add(new SolicitudViewModel
                    {
                        Solicitante = sol.UserProfile.Name,
                        EmailSolicitante = sol.UserProfile.UserName,
                        FechaCreacion = sol.SS_Fecha,
                        Solicitud = sol.SS_Id,
                        Status = x.Invoke(sol.ST_Id),
                        TelefonoSolicitante = sol.AN_Anuncios.AN_Telefono  , // "No Telefono",
                        StatusId = sol.ST_Id
                    });
                });
            }
            //mysol.OrderByDescending(sol => sol.FechaCreacion);
            return View(mysol);
        }

        [HttpPost]
        [AjaxAuthorizeAttribute(Roles = "Admin, Users")]
        public ActionResult TakeService(FormCollection form)
        {
            if (form[0] != null)
            {
                int anuncioId = int.Parse(form[0]);
                using (var db = new Entities())
                {
                    //Si es administrador
                    if (Roles.IsUserInRole(WebSecurity.CurrentUserName, "Admin"))
                    {
                        return Json(new { Message = "Estimado usuario, le informamos que su cuenta administrador no le permite solicitar servicios. Utilice su cuenta de usuario regular." });
                    }

                    //Si existe una solicitud sin iniciar atención
                    var existSolicitud = db.SS_SolicitudServicio.Any(c => c.AN_Id == anuncioId && c.ST_Id == 1 && c.UserId == WebSecurity.CurrentUserId);
                    if (existSolicitud)
                    {
                        return Json(new { Message = "Estimado usuario, le informamos que ya cuenta con una solicitud activa para este anuncio que desea solicitar, por favor póngase en contacto con el anunciante." });
                    }

                    //Si es un propio anuncio
                    var anuncio = db.AN_Anuncios.Find(anuncioId);
                    if (anuncio.UserId == WebSecurity.CurrentUserId)
                    {
                        return Json(new { Message = "Estimado usuario, le informamos que no es posible hacer solicitudes a sus propios anuncios." });
                    }

                    var solicitud = db.SS_SolicitudServicio.Add(new SS_SolicitudServicio
                    {
                        AN_Id = anuncioId,
                        ST_Id = 1,
                        SS_Fecha = System.DateTime.Now,
                        UserId = WebSecurity.CurrentUserId
                    });
                    var solicitudcreada = db.SaveChanges<SS_SolicitudServicio>(solicitud);
                    if (solicitudcreada != null)
                    {
                        SendEmailNotification(solicitudcreada, false, 1);
                    }
                }
            }
            return null;
        }

        [AjaxAuthorizeAttribute(Roles = "Users")]
        public ActionResult SolicitudRequest()
        {
            var mysol = new List<SolicitudViewModel>();
            using (var db = new Entities())
            {
                var solicitudes = db.SS_SolicitudServicio.OrderByDescending(c => c.SS_Id).Where(c => c.AN_Anuncios.UserId == WebSecurity.CurrentUserId);
                Func<int, string> x = value =>
                {
                    switch (value)
                    {
                        case 1: return "Activo";
                        case 2: return "Cancelado";
                        case 3: return "Realizado";
                        case 4: return "En espera de Review";
                        case 5: return "Completado";
                        case 6: return "Iniciar Tarea";
                        case 7: return "A revisión";
                        case 8: return "Eliminado";
                        case 9: return "Expirado";
                        default: return "";
                    }
                };

                solicitudes.ToList().ForEach((sol) =>
                {

                    mysol.Add(new SolicitudViewModel
                    {
                        TituloAnuncio = sol.AN_Anuncios.AN_Titulo,
                        Solicitante = sol.UserProfile.Name,
                        EmailSolicitante = sol.UserProfile.UserName,
                        FechaCreacion = sol.SS_Fecha,
                        Solicitud = sol.SS_Id,
                        Status = x.Invoke(sol.ST_Id),
                        TelefonoSolicitante = sol.UserProfile.NumeroTelefono, // sol.AN_Anuncios.AN_Telefono,
                        StatusId = sol.ST_Id
                    });
                });
            }
            return View(mysol);
        }

        internal class Updating
        {
            public string Message { get; set; }

        }

        [HttpGet]
        public ActionResult ChangeStatus(int Solicitud, int Status)
        {
            Updating update = new Updating() { Message = "La solicitud número " + Solicitud.ToString() + " ha sido cancelada." };
            using (var db = new Entities())
            {
                var solicitud = db.SS_SolicitudServicio.Find(Solicitud);
                solicitud.ST_Id = Status;
                db.Entry(solicitud).State = EntityState.Modified;
                db.SaveChanges();
                if (Status == 3)
                {
                    SendEmailNotification(solicitud, true, Status);
                }
                else if (Status == 2)
                {
                    SendEmailNotification(solicitud, false, Status);
                }
            }


            if (Request.IsAjaxRequest())
            {
                return Json(update.SerializeToJson(), JsonRequestBehavior.AllowGet);
            }

            return View();

        }

        //
        // GET: /SolicitudServicio/Details/5
        [Authorize(Roles = "Users")]
        public ActionResult Details(int id = 0)
        {
            SS_SolicitudServicio ss_solicitudservicio = db.SS_SolicitudServicio.Find(id);
            if (ss_solicitudservicio == null)
            {
                return HttpNotFound();
            }
            return View(ss_solicitudservicio);
        }

        //
        // GET: /SolicitudServicio/Create
        [Authorize(Roles = "Users")]
        public ActionResult Create()
        {
            ViewBag.AN_Id = new SelectList(db.AN_Anuncios, "AN_Id", "AN_Titulo");
            ViewBag.ST_Id = new SelectList(db.ST_Estatus, "ST_Id", "ST_Descripcion");
            return View();
        }

        //
        // POST: /SolicitudServicio/Create
        [Authorize(Roles = "Users")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SS_SolicitudServicio ss_solicitudservicio)
        {
            if (ModelState.IsValid)
            {
                db.SS_SolicitudServicio.Add(ss_solicitudservicio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AN_Id = new SelectList(db.AN_Anuncios, "AN_Id", "AN_Titulo", ss_solicitudservicio.AN_Id);
            ViewBag.ST_Id = new SelectList(db.ST_Estatus, "ST_Id", "ST_Descripcion", ss_solicitudservicio.ST_Id);
            return View(ss_solicitudservicio);
        }

        //
        // GET: /SolicitudServicio/Edit/5
        [Authorize(Roles = "Users")]
        public ActionResult Edit(int id = 0)
        {
            SS_SolicitudServicio ss_solicitudservicio = db.SS_SolicitudServicio.Find(id);
            if (ss_solicitudservicio == null)
            {
                return HttpNotFound();
            }
            ViewBag.AN_Id = new SelectList(db.AN_Anuncios, "AN_Id", "AN_Titulo", ss_solicitudservicio.AN_Id);
            ViewBag.ST_Id = new SelectList(db.ST_Estatus, "ST_Id", "ST_Descripcion", ss_solicitudservicio.ST_Id);
            return View(ss_solicitudservicio);
        }

        //
        // POST: /SolicitudServicio/Edit/5
        [Authorize(Roles = "Users")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SS_SolicitudServicio ss_solicitudservicio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ss_solicitudservicio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

SMAWeb/Views/SolicitudServicio/Details.cshtml
@model SMAWeb.Models.SS_SolicitudServicio

@{
    ViewBag.Title = "Detalle de Solicitud de Servicio";
}

<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Detalle de Solicitud de Servicio</h3>
            </div>
            <div class="form-horizontal">
                <div class="control-group" style="margin-bottom: 0px;">
                    <label class="control-label" style="padding-top: 0px; width:280px"><strong>@Html.DisplayNameFor(model => model.SS_Id)</strong></label>
                    <div class="controls" style="margin-left: 300px;">
                        @Html.DisplayFor(model => model.SS_Id)
                    </div>
                </div>
                <div class="control-group" style="margin-bottom: 0px;">
                    <label class="control-label" style="padding-top: 0px; width:280px"><strong>@Html.DisplayNameFor(model => model.AN_Id)</strong></label>
                    <div class="controls" style="margin-left: 300px;">
                        @Html.DisplayFor(model => model.AN_Id)
                    </div>
                </div>
                <div class="control-group" style="margin-bottom: 0px;">
                    <label class="control-label" style="padding-top: 0px; width:280px"><strong>@Html.DisplayNameFor(model => model.SS_Fecha)</strong></label>
                    <div class="controls" style="margin-left: 300px;">
                        @Html.DisplayFor(model => model.SS_Fecha)
                    </div>
                </div>
                <div class="control-group" style="margin-bottom: 0px;">
                    <label class="control-label" style="padding-top: 0px; width:280px"><strong>@Html.DisplayNameFor(model => model.ST_Id)</strong></label>
                    <div class="controls" style="margin-left: 300px;">
                        @Html.DisplayFor(model => model.ST_Estatus.ST_Descripcion)
                    </div>
                </div>
                <div class="control-group" style="margin-bottom: 0px;">
                    <label class="control-label" style="padding-top: 0px; width:280px"><strong>@Html.DisplayName("Nombre de Usuario")</strong></label>
                    <div class="controls" style="margin-left: 300px;">
                        @Html.DisplayFor(model => model.UserProfile.Name)
                    </div>
                </div>
            </div>
            <br />
            <p>
                @*@Html.ActionLink("Edit", "Edit", new { id=Model.PrimaryKey  }) | *@
                @Html.ActionLink("Regresar", "Index")
            </p>
        </div>
    </div>
</div>

SMAWeb/Views/SolicitudServicio/Index.cshtml
@model IEnumerable<SMAWeb.Models.SolicitudViewModel>

@{
    ViewBag.Title = "Index";
}

<link href="@Url.Content("~/Content/jpages/jPages.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/jpages/animate.css")" rel="stylesheet" type="text/css" />
@*<link href="@Url.Content("~/Content/jpages/style.css")" rel="stylesheet" type="text/css" />*@
<script src="@Url.Content("~/Scripts/jpage/jPages.min.js")" type="text/javascript"></script>


<br />
<div class="container">
    <div class="row-fluid margin-bottom-10">

        <div class="another-page">
            <div class="headline">
                <h3>Formulario Solicitud de Servicio</h3>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>

                            @Html.DisplayNameFor(model => model.Solicitud)
                        </th>
                        <th>

                            @Html.DisplayNameFor(model => model.FechaCreacion)
                        </th>
                        <th>

                            @Html.DisplayNameFor(model => model.Solicitante)
                        </th>
                        <th>

                            @Html.DisplayNameFor(model => model.EmailSolicitante)
                        </th>
                        <th>

                            @Html.DisplayNameFor(model => model.TelefonoSolicitante)
                        </th>
                        <th>

                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                     
                    </tr>
                </thead>
                <tbody id="divBody">


                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                               @* @Html.DisplayFor(modelItem => item.Solicitud)*@

                                @Html.ActionLink(item.Solicitud.ToString(), "Details", "SolicitudServicio", new { id = item.Solicitud }, null)

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaCreacion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Solicitante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmailSolicitante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TelefonoSolicitante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
         
                        </tr>
                    }
                </tbody>

                <tfoot>
                    <tr>
                        <td colspan="7">
                            <div class="holder" style="float: left">
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<script>
    var $jpage = jQuery.noConflict();
    $jpage(function () {
        $jpage("div.holder").jPages({
            containerID: "divBody",
            //              previous: "?",
            //              next: "?",
            first: "Primera",
            previous: "Anterior",
            next: "Siguiente",
            last: "Última",
            perPage: 5,
            delay: 20
        });
    });
</script>

SMAWeb/Views/SolicitudServicio/SolicitudRequest.cshtml
@model IEnumerable<SMAWeb.Models.SolicitudViewModel>

    @{
        ViewBag.Title = "Tus Solicitudes de Servicios";
    }

    <link href="@Url.Content("~/Content/jpages/jPages.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jpages/animate.css")" rel="stylesheet" type="text/css" />
    @*<link href="@Url.Content("~/Content/jpages/style.css")" rel="stylesheet" type="text/css" />*@
    <script src="@Url.Content("~/Scripts/jpage/jPages.min.js")" type="text/javascript"></script>


    <br />
    <div class="container">
        <div class="row-fluid margin-bottom-10">

            <div class="another-page">
                <div class="headline">
                    <h3>Mis Solicitudes de Servicios</h3>
                </div>
                <div class="span12">
                    @if (Model.Count() > 0)
                    {

                        <table class="table-hover" style="width: 100%">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <div class="row-fluid">
                                            <div class="span12 booking-blocks" style="padding: 10px; margin-bottom: 15px;">
                                                <div class="span9">

                                                    <div style="overflow: hidden;">

                                                        <h4>@Html.DisplayFor(modelItem => item.TituloAnuncio) </h4>
                                                        <h5> - Estado: @Html.DisplayFor(modelItem => item.Status)</h5>
                                                        <ul class="unstyled inline">
                                                            <li><i class="icon-user"></i>@Html.DisplayFor(modelItem => item.Solicitante)</li>&nbsp;
                                                            <li><i class="icon-envelope"></i>@Html.DisplayFor(modelItem => item.EmailSolicitante)</li>
                                                        </ul>
                                                        <ul class="unstyled inline">
                                                            <li><i class="icon-calendar"></i>@Html.DisplayFor(modelItem => item.FechaCreacion)</li>&nbsp;
                                                            <li><i class="icon-bookmark"></i>@Html.DisplayFor(modelItem => item.TelefonoSolicitante)</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <div class="span3">
                                                    @if (item.StatusId == 1)
                                                    {
                                                        <a class="btn-u btn-u-orange btn-block" attrurl="@Url.Action("ChangeStatus", "SolicitudServicio", new { Solicitud = item.Solicitud, Status = 6 })" id="starttask"><i class="icon-white icon-plus"></i> Iniciar Tarea</a>
                                                        <a class="btn-u btn-u-orange btn-block" attrurl="@Url.Action("ChangeStatus", "SolicitudServicio", new { Solicitud = item.Solicitud, Status = 2 })" href="javascript:CancelTask()" id="canceltask"><i class="icon-white icon-remove-circle"></i> Cancelar Tarea</a>
                                                    }

                                                    else if (item.StatusId == 6)
                                                    {
                                                        <a class="btn-u btn-u-orange btn-block" attrurl="@Url.Action("ChangeStatus", "SolicitudServicio", new { Solicitud = item.Solicitud, Status = 3 })" id="processtask"><i class="icon-white icon-ok"></i>Tarea Completada</a>
                                                    }
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }

                        </table>
                    }
                    else
                    {
                        <div id="DivNoAnuncios" class="bold large span12" style="padding: 5px; display: block;">
                            <h4>No cuenta con solicitudes de Servicios aún.</h4> <br />
                        </div>
                        <h4>Le invitamos a crear sus <a class="color-green" href="@Url.Action("Create", "Anuncios")">&nbsp;anuncios gratuitos&nbsp;</a>en este su portal de servicios persona a persona.</h4>
                        <h4>Service Market le ofrece:</h4>
                        <ul class="unstyled">
                            <li><i class="icon-ok color-green"></i> Publicación de anuncios totalmente grátis</li>
                            <li><i class="icon-ok color-green"></i> Contratar los mejores servicios persona a persona</li>
                            <li><i class="icon-ok color-orange"></i> Comentarios después de cada servicio contratado</li>

                        </ul>

                    }
                </div>
                <div class="span12">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- MisSolicitudes -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-3305573167906515"
                         data-ad-slot="3788765584"
                         data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div id="message"></div>
    <script src="~/Scripts/SMA.js"></script>
    <script>

        var $jpage = jQuery.noConflict();
        $jpage(function () {
            $jpage("div.holder").jPages({
                containerID: "divBody",
                //              previous: "?",
                //              next: "?",
                first: "Primera",
                previous: "Anterior",
                next: "Siguiente",
                last: "Última",
                perPage: 5,
                delay: 20
            });
        });

        jQuery(document).ready(function () {
            jQuery('#starttask, #processtask').click(function () {
                var url = jQuery(this).attr('attrurl');

                $.ajax({
                    url: url,
                    type: 'get',
                    beforeSend: function () {
                        showProgress('@Url.Content("~/images/loading.gif")');
                    },
                    complete: function (data) {
                        hideProgress();
                    },
                    success: function (data) {
                        setTimeout(3000);
                        window.location = '@Url.Action("SolicitudRequest", "SolicitudServicio")';
                    },
                    error: function (xhr) {
                        if (xhr.status == 403) {

                        }
                    }
                });
            });

        });

        var $ki = jQuery.noConflict();

        function CancelTask(Solicitud, Status) {
            var url = $ki("#canceltask").attr('attrurl');
            SOLICITUD.CancelTask(Solicitud, Status, url);
        };

        function showProgress(loadingImgSrc) {
            $ki.blockUI({
                message: '<p>Por favor espere mientra se procesa la solicitud...</p><img src="' + loadingImgSrc + '" /> <br>',
                css: {
                    width: '450px',
                    border: 'none',
                    padding: '15px',
                    backgroundColor: '#fafafa',
                    'border-radius': '10px',
                    opacity: .95,
                    color: '#000',
                    'font-size': '18px',
                    'box-shadow': '0px 0px 12px rgba(0,0,0,.6)',
                    'z-index': '9999'
                }
            });
        }

        function hideProgress() {
            $ki.unblockUI();
        }

    </script>